const carData = {
  makes: [
    { label: "Toyota", value: "toyota" },
    { label: "Ford", value: "ford" },
    { label: "BMW", value: "bmw" },
    { label: "Honda", value: "honda" },
    { label: "Hyundai", value: "hyundai" },
    { label: "Chevrolet", value: "chevrolet" },
    { label: "Mazda", value: "mazda" },
    { label: "KIA", value: "kia" },
    { label: "Nissan", value: "nissan" },
    { label: "Fiat", value: "fiat" },
    { label: "Subaru", value: "subaru" },
    { label: "Audi", value: "audi" },
    { label: "Jeep", value: "jeep" },
    { label: "Tesla", value: "tesla" },
    { label: "Volkswagen", value: "volkswagen" },
    { label: "Mercedes", value: "mercedes" },
    { label: "Dodge", value: "dodge" },
    { label: "Volvo", value: "volvo" },
    { label: "Lexus", value: "lexus" },
    { label: "Porshe", value: "porshe" },
    { label: "Mitsubishi", value: "mitsubishi" },
    { label: "Jaguar", value: "jaguar" },
    { label: "Infiniti", value: "infiniti" },
    { label: "Acura", value: "acura" },
    { label: "Buick", value: "buick" },
    { label: "GMC", value: "gmc" },
    { label: "Ram", value: "ram" },
    { label: "Suzuki", value: "suzuki" },
  ],
  models: {
    toyota: [
      { label: "Corolla", value: "corolla" },
      { label: "Camry", value: "camry" },
      { label: "RAV4", value: "rav4" },
      { label: "Yaris", value: "yaris" },
      { label: "Highlander", value: "highlander" },
      { label: "Hilux", value: "hilux" },
      { label: "Sienna", value: "sienna" },
      { label: "Prius", value: "prius" },
      { label: "Tundra", value: "tundra" },
    ],
    ford: [
      { label: "Focus", value: "focus" },
      { label: "Mustang", value: "mustang" },
      { label: "Escape", value: "escape" },
      { label: "Fiesta", value: "fiesta" },
      { label: "Maverick", value: "maverick" },
      { label: "Bronco", value: "bronco" },
      { label: "F-150", value: "f150" },
      { label: "Ranger", value: "ranger" },
      { label: "Transit", value: "transit" },
    ],
    bmw: [
      { label: "3 Series", value: "3series" },
      { label: "5 Series", value: "5series" },
      { label: "X5", value: "x5" },
    ],
    honda: [
      { label: "Civic", value: "civic" },
      { label: "Accord", value: "accord" },
      { label: "CR-V", value: "crv" },
      { label: "Odyssey", value: "odyssey" },
      { label: "Fit", value: "fit" },
      { label: "HR-V", value: "hrv" },
    ],
    hyundai: [
      { label: "Elantra", value: "elantra" },
      { label: "Tucson", value: "tucson" },
      { label: "Santa Fe", value: "santafe" },
      { label: "Kona", value: "kona" },
      { label: "Palisade", value: "palisade" },
      { label: "Sonata", value: "sonata" },
    ],
    chevrolet: [
      { label: "Cruze", value: "cruze" },
      { label: "Malibu", value: "malibu" },
      { label: "Equinox", value: "equinox" },
      { label: "Sonic", value: "sonic" },
      { label: "Silverado", value: "silverado" },
      { label: "Impala", value: "impala" },
      { label: "Traverse", value: "traverse" },
      { label: "Blazer", value: "blazer" },
      { label: "Colorado", value: "colorado" },
      { label: "Bolt", value: "bolt" },
      { label: "Tahoe", value: "tahoe" },
    ],
    mazda: [
      { label: "Mazda 3", value: "mazda3" },
      { label: "Mazda 6", value: "mazda6" },
      { label: "CX-5", value: "cx5" },
      { label: "CX-9", value: "cx9" },
      { label: "CX-7", value: "cx7" },
      { label: "CX-50", value: "cx50" },
      { label: "CX-90", value: "cx90" },
    ],
    kia: [
      { label: "Rio", value: "rio" },
      { label: "Sportage", value: "sportage" },
      { label: "Sorento", value: "sorento" },
      { label: "Optima", value: "optima" },
      { label: "Sedona", value: "sedona" },
      { label: "K5", value: "k5" },
      { label: "Sorento", value: "sorento" },
    ],
    nissan: [
      { label: "Altima", value: "altima" },
      { label: "Sentra", value: "sentra" },
      { label: "Rogue", value: "rogue" },
      { label: "Versa", value: "versa" },
      { label: "Leaf", value: "leaf" },
      { label: "NV200", value: "nv200" },
      { label: "Rogue", value: "rogue" },
    ],
    fiat: [
      { label: "500", value: "500" },
      { label: "Panda", value: "panda" },
      { label: "Tipo", value: "tipo" },
    ],
    subaru: [
      { label: "Legacy", value: "legacy" },
      { label: "Impreza", value: "impreza" },
      { label: "Forester", value: "forester" },
      { label: "Crosstrek", value: "crosstrek" },
      { label: "Outback", value: "outback" },
    ],
    audi: [
      { label: "A6", value: "a6" },
      { label: "Q5", value: "q5" },
      { label: "A6", value: "a6" },
    ],
    tesla: [
      { label: "Model X", value: "modelx" },
      { label: "Model S", value: "models" },
      { label: "Model 3", value: "model3" },
      { label: "Model Y", value: "modely" },
    ],
    volkswagen: [
      { label: "Golf", value: "golf" },
      { label: "Passat", value: "passat" },
      { label: "Tiguan", value: "tiguan" },
    ],
    dodge: [
      { label: "Charger", value: "charger" },
      { label: "Durango", value: "durango" },
    ],
    lexus: [
      { label: "ES", value: "es" },
      { label: "RX", value: "rx" },
      { label: "NX 350h", value: "nx350h" },
    ],
    volvo: [
      { label: "S60", value: "s60" },
      { label: "XC60", value: "xc60" },
      { label: "XC90", value: "xc90" },
    ],
    mitsubishi: [
      { label: "Eclipse", value: "eclipse" },
      { label: "Outlander", value: "outlander" },
    ],
    jaguar: [
      { label: "XE", value: "xe" },
      { label: "F-Pace", value: "fpace" },
    ],
    infiniti: [
      { label: "Q50", value: "q50" },
      { label: "QX60", value: "qx60" },
    ],
    acura: [
      { label: "MDX", value: "mdx" },
      { label: "RDX", value: "rdx" },
    ],
    buick: [
      { label: "Encore", value: "encore" },
      { label: "Envista", value: "envista" },
      { label: "Envision", value: "envision" },
    ],
    gmc: [
      { label: "Yukon", value: "yukon" },
      { label: "Canyon", value: "canyon" },
      { label: "Terrain", value: "terrain" },
      { label: "Acadia", value: "acadia" },
    ],
    suzuki: [
      { label: "Swift", value: "swift" },
      { label: "Vitara", value: "vitara" },
    ],
    ram: [
      { label: "ProMaster", value: "promaster" },
      { label: "1500", value: "1500" },
    ],
    jeep: [
      { label: "Grand Cherokee", value: "grandcherokee" },
      { label: "Compass", value: "compass" },
      { label: "Wrangler", value: "wrangler" },
    ],
  },
};

export default carData;
